name: dash_env  # You can rename this to whatever you'd like
channels:
  - conda-forge
dependencies:
  - python=3.9  # Specify the Python version if necessary
  - streamlit=1.39.0
  - folium=0.17.0
  - streamlit-folium
  - pandas
  - numpy
  - matplotlib
  - altair